Resources:
  TicketTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TicketTable
      AttributeDefinitions:
        - AttributeName: TicketId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: TicketId
          KeyType: HASH
